<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ $entry->title }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 40px;
        }

        .header {
            border-bottom: 3px solid #3b82f6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #3b82f6;
            margin-bottom: 10px;
        }

        h1 {
            font-size: 28px;
            color: #1f2937;
            margin-bottom: 10px;
        }

        .meta {
            color: #6b7280;
            font-size: 12px;
            margin-top: 10px;
        }

        .content {
            margin: 30px 0;
            font-size: 14px;
            line-height: 1.8;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .stats {
            display: flex;
            gap: 20px;
            margin: 30px 0;
            padding: 20px;
            background: #f3f4f6;
            border-radius: 8px;
        }

        .stat {
            flex: 1;
            text-align: center;
        }

        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #3b82f6;
        }

        .stat-label {
            font-size: 12px;
            color: #6b7280;
            margin-top: 5px;
        }

        .tags {
            margin-top: 20px;
        }

        .tag {
            display: inline-block;
            padding: 5px 12px;
            margin-right: 8px;
            margin-bottom: 8px;
            background: #dbeafe;
            color: #3b82f6;
            border-radius: 20px;
            font-size: 12px;
        }

        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #9ca3af;
            font-size: 11px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="logo">LUMINA</div>
        <h1>{{ $entry->title }}</h1>
        <div class="meta">
            Created: {{ $entry->created_at->format('F j, Y \a\t g:i A') }}
        </div>
    </div>

    <div class="stats">
        <div class="stat">
            <div class="stat-value">{{ str_word_count($entry->content) }}</div>
            <div class="stat-label">Words</div>
        </div>
        <div class="stat">
            <div class="stat-value">{{ strlen($entry->content) }}</div>
            <div class="stat-label">Characters</div>
        </div>
        <div class="stat">
            <div class="stat-value">{{ $entry->tags->count() }}</div>
            <div class="stat-label">Tags</div>
        </div>
    </div>

    <div class="content">
        {{ $entry->content }}
    </div>

    @if($entry->tags && $entry->tags->count() > 0)
        <div class="tags">
            @foreach($entry->tags as $tag)
                <span class="tag">#{{ $tag->name }}</span>
            @endforeach
        </div>
    @endif

    <div class="footer">
        Generated by {{ config('app.name') }} on {{ date('F j, Y') }}
    </div>
</body>

</html>